- name: Install k3s master
  shell: curl -sfL https://get.k3s.io | sh - --tls-san {{ ansible_default_ipv4.address }}
  args:
    creates: /usr/local/bin/k3s # Ensure idempotency
- name: Get k3s token
  shell: sudo cat /var/lib/rancher/k3s/server/node-token
  register: k3s_token
- name: Set k3s token as a fact
  set_fact:
    k3s_token: "{{ k3s_token.stdout }}"
- name: Debug k3s_token fact
  debug:
    var: hostvars['k3s-master']['k3s_token']
